### ISSUE TITLE
Installation doesn't work on mac

### ISSUE THREAD

**Issue by MaximusMellberg** [edgarcosta/ToricControlledReduction#1]
I attempted to use this on the mac command line with Sage providing the dependencies, I followed the steps outlined in the README file and everything seems to work up until step 4 (running the make file) where I get errors in various locations saying "fatal error: 'omp.h' file not found".

**Comment by edgarcosta** [comment]
Did you mean to post here: https://github.com/edgarcosta/controlledreduction/?

This library https://github.com/edgarcosta/ToricControlledReduction/ doesn't call `omp.h`

Also, if you have sage, you could call use: https://github.com/edgarcosta/pycontrolledreduction

**Comment by MaximusMellberg** [comment]
My bad, I got the two confused, I will move the issue to that repository. Additionally I seem to be getting the same error with pycontrolled reduction so I'll open another issue on that repository as well. Thanks for the quick response
